
spring: 
  kafka:
    producer:
      bootstrap-servers: kafka:9092
    consumer:
      bootstrap-servers: kafka:9092 
      
              
mongodb:
  uri:
    read: mongodb://sa:${MONGODB_PASS_READ:invalidPassword}@ms-client-read-db:27017/mongo-read-db?authSource=admin
    write: mongodb://sa:${MONGODB_PASS_WRITE:invalidPassword}@ms-client-write-db:27017/mongo-write-db?authSource=admin
 