
spring: 
  kafka:
    producer:
      bootstrap-servers: kafka:9092
    consumer:
      bootstrap-servers: kafka:9092 
      
  datasource:
    url: jdbc:postgresql://ms-reservation-sql-db:5432/reservationSqlDb  
        
  data:
    redis:
      host: ms-reservation-redis-db
      port: 6379     
              
    mongodb:
      uri: mongodb://sa:${MONGODB_PASS_WRITE:invalidPassword}@ms-reservation-write-db:27017/mongo-write-db?authSource=admin
 