
spring: 
  kafka:
    producer:
      bootstrap-servers: kafka:9092
    consumer:
      bootstrap-servers: kafka:9092 
        
  data:
    redis:
      host: ms-seat-redis-db
      port: 6379     
              
mongodb:
  uri:
    read: mongodb://sa:${MONGODB_PASS_READ:invalidPassword}@ms-seat-read-db:27017/mongo-read-db?authSource=admin
    write: mongodb://sa:${MONGODB_PASS_WRITE:invalidPassword}@ms-seat-write-db:27017/mongo-write-db?authSource=admin
 